# Copyright (c) 2023, Henrik Söderlund

remote:
  host_alias: robot
  host_name: 192.168.1.227
  user: pi
  port: 22
  identity_file: ~/.ssh/id_rsa
arduino:
  serial: '/dev/ttyACM0'
  baud_rate: '115200'
  platform: 'per1234:sam:arduino_due_x_dbg'
nodes:
  serial_can_logger:
    log_file: 'logs/serial_can_logger/data.asc'
